import Head from "next/head";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import {
  IoChevronDownOutline,
  IoChevronUpOutline,
  IoCallOutline,
  IoChatbubbleEllipsesOutline,
} from "react-icons/io5";
import { MdLocationPin } from "react-icons/md";
import SideDrawer from "../components/common/SideDrawer";
import { SelectField } from "./../components/common/input";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import { FreeMode, Navigation, Thumbs } from "swiper";
import Axios from "../libs/axios";
import { Link as ScrollLink, animateScroll as scroll } from "react-scroll";
import Product from "../components/product/Product";

export default function Home() {
  const [cities, setCities] = useState([]);
  const [currentCity, setCurrentCity] = useState("");
  const [searchKey, setSearchKey] = useState({ region: "", cities: [] });
  const [isSearching, setIsSearching] = useState(false);
  const [products, setProducts] = useState([]);
  const [searchProducts, setSearchProducts] = useState([]);
  const [product, setProduct] = useState(null);
  const [loading, setLoading] = useState(false);
  const drawer = React.useRef(null);

  const scrollToTop = () => {
    scroll.scrollToTop();
  };
  const handleRegionChange = (e) => {
    setSearchKey((state) => (state = { ...state, region: e.target.value }));
  };
  const handleCityChange = (e) => {
    setIsSearching(true);
    setCurrentCity((state) => (state = e.target.value));
    Axios.get("/apartments")
      .then((res) => {
        const results = res.data.filter((r) => {
          if (
            r.region.toLowerCase() === searchKey.region.toLowerCase() &&
            r.city.toLowerCase() === e.target.value.toLowerCase()
          ) {
            return r;
          }
        });
        setSearchProducts((state) => (state = [...results]));
      })
      .catch((err) => {
        console.log(err);
      });
  };
  const viewDetails = (data) => {
    setProduct((p) => (p = data));
    drawer.current.open();
  };
  const resetHandler = (e) => {
    setIsSearching(false);
    setSearchKey((state) => (state = { region: "", cities: [] }));
  };
  const loadMore = () => {
    setLoading(true);
    Axios.get("/apartments")
      .then((res) => {
        const ln = products.length;
        const data = res.data.slice(ln, ln + 3);
        setTimeout(() => {
          setLoading(false);
          setProducts((p) => (p = [...p, ...data]));
        }, 2000);
      })
      .catch((err) => {
        console.log(err);
      });
  };
  useEffect(() => {
    Axios.get("/cities")
      .then((res) => {
        setCities((c) => (c = [...res.data]));
        // console.log(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);
  useEffect(() => {
    if (searchKey.region) {
      const result = cities.find((r) => r.region === searchKey.region);
      setSearchKey((state) => (state = { ...state, cities: result.cities }));
    }
  }, [searchKey.region, cities]);
  useEffect(() => {
    Axios.get("/apartments")
      .then((res) => {
        const data = res.data.slice(0, 3);
        setProducts((p) => (p = [...data]));
        console.log(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);
  return (
    <div className="home">
      <Head>
        <title>Seydel Apartments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="home__banner">
        <div className="home__banner__nav">
          <div className="home__banner__nav__brand">
            <Link href="/login">
              <a>
                Seydel <span>Apartments</span>
              </a>
            </Link>
          </div>
          <nav className="home__banner__nav__links">
            <ul>
              <li>
                <ScrollLink
                  to="aboutSection"
                  spy={true}
                  smooth={true}
                  offset={-70}
                  duration={1000}
                >
                  About Us
                </ScrollLink>
              </li>
              <li>
                <ScrollLink
                  to="contactSection"
                  spy={true}
                  smooth={true}
                  offset={-70}
                  duration={1000}
                >
                  Contact Us
                </ScrollLink>
              </li>
              <li>
                <Link href="/signin">
                  <a className="button">login</a>
                </Link>
              </li>
            </ul>
          </nav>
        </div>
        <div className="home__banner__cta">
          <h2>The Landlord</h2>
          <p>
            Renting apartment should not be a <span>hustle!</span>
          </p>
          <ScrollLink
            to="roomsSection"
            spy={true}
            smooth={true}
            offset={-70}
            duration={1000}
            className="btn__down"
          >
            <IoChevronDownOutline />
          </ScrollLink>
        </div>
      </div>

      <section className="home__container" id="roomsSection">
        <aside className="home__container__aside">
          <h3>Location</h3>
          <div className="home__container__aside__filter">
            <SelectField
              label="Region"
              placeholder="Select Region"
              name="region"
              id="region"
              value={searchKey.region}
              onChange={handleRegionChange}
            >
              {cities.map((r) => (
                <option value={r.region} key={r.region}>
                  {r.region}
                </option>
              ))}
            </SelectField>

            <SelectField
              label="City"
              placeholder="Select City"
              name="city"
              id="city"
              value={currentCity}
              onChange={handleCityChange}
            >
              {searchKey.cities.map((c) => (
                <option value={c} key={c}>
                  {c}
                </option>
              ))}
            </SelectField>

            <div className="load__more">
              <button type="button" onClick={resetHandler}>
                Clear Filter
              </button>
            </div>
          </div>
        </aside>

        <main className="home__container__main">
          {isSearching && searchProducts.length > 0 ? (
            searchProducts.map((p) => (
              <Product viewDetails={viewDetails} room={p} key={p.title} />
            ))
          ) : !isSearching && products.length > 0 ? (
            products.map((p) => (
              <Product viewDetails={viewDetails} room={p} key={p.title} />
            ))
          ) : (
            <h1 className="no__record">No record found!</h1>
          )}
          {loading && <p className="no__record">Loading...</p>}
          <div className="load__more">
            <button type="button" onClick={loadMore}>
              view more
            </button>
          </div>
        </main>
      </section>
      <section className="home__about" id="aboutSection">
        <div className="home__about__story">
          <h3 className="home__about__story__header">
            What makes Seydel Apartments <span>different</span>?
          </h3>
          <article className="home__about__story__article">
            <p>
              We are your number one source for all housing solutions (rentals).
              We are dedicated to giving you the very best of apartments, with a
              focus on three characteristics, ie: dependability, customer
              service and uniqueness.
            </p>
            <p>
              {` We hope you enjoy our service as much as we enjoy offering them to
              you. If you have any questions or comments, please don't hesitate
              to contact us.`}
            </p>
          </article>
        </div>
        <div className="home__about__image">
          <div className="home__about__image__cta">
            <h1>The</h1>
            <h1>Difference!</h1>
          </div>
        </div>
      </section>
      <section className="home__contact" id="contactSection">
        <div className="home__contact__top">
          <div className="home__contact__top__image"></div>
          <div className="home__contact__top__cta">
            <h1>Meet Us</h1>
            <p>
              {`Want to get in touch? We love to hear from you. Here's is how you can reach us...`}{" "}
            </p>
          </div>
        </div>
        <div className="home__contact__bottom">
          <div className="home__contact__bottom__content">
            <div className="home__contact__bottom__content__header">
              {<IoCallOutline />}
              <p>Talk to a representative</p>
            </div>
            <p>
              Interested in Seydel Apartments? Just pick up the phone and call
              any of our reps.
            </p>
            <a href="tel:+233557467520">+233 55 746 7520</a>
          </div>

          <div className="home__contact__bottom__content">
            <div className="home__contact__bottom__content__header">
              {<IoChatbubbleEllipsesOutline />}
              <p>Contact customer support</p>
            </div>
            <p>{`Sometimes you need a help for your rentals issues. Don't worry...we are here for you.`}</p>
            <a href="tel:+233265518694">+233 26 551 8694</a>
          </div>
        </div>
      </section>
      <footer className="footer">
        <strong>
          &copy;{new Date().getUTCFullYear()} Seydel Apartments. All Rights
          Reserved
        </strong>
      </footer>
      {/* <button className="btn__up">{<IoChevronUpOutline />}</button> */}
      <SideDrawer title={product && product.title} ref={drawer}>
        <div className="product__view">
          <div className="product__view__image">
            <Swiper
              loop={false}
              spaceBetween={10}
              navigation={true}
              modules={[FreeMode, Navigation]}
              className="product__view__image__wrapper"
            >
              {product &&
                product.images.map((image) => (
                  <SwiperSlide key={image}>
                    <img src={image} alt="property image" />
                  </SwiperSlide>
                ))}
            </Swiper>
          </div>
          <div className="product__view__info">
            <div className="product__details">
              <div className="product__details__top">
                <h4 className="title">{product && product.title}</h4>
                <p>{product && product.description}</p>
              </div>
              <div className="product__details__bottom">
                <MdLocationPin />
                <span>
                  {product && product.region}, {product && product.city}
                </span>
                ,
              </div>
              <Link href="">
                <a className="pay__btn">Pay</a>
              </Link>
            </div>
            <div className="product__price">
              <strong>GHS {product && product.price}</strong>
              <p>per month</p>
            </div>
          </div>
        </div>
      </SideDrawer>
    </div>
  );
}
